//autogenerated:yes
//nolint:revive,govet,errcheck
package development

import (
	"testing"

	"github.com/stretchr/testify/require"
)

func TestEnum_MAV_MANUAL_INPUT_SOURCE(t *testing.T) {
	t.Run("zero", func(t *testing.T) {
		var e MAV_MANUAL_INPUT_SOURCE
		e.UnmarshalText([]byte{})
		e.MarshalText()
		e.String()
	})

	t.Run("first entry", func(t *testing.T) {
		enc, err := MAV_MANUAL_INPUT_SOURCE_NONE.MarshalText()
		require.NoError(t, err)

		var dec MAV_MANUAL_INPUT_SOURCE
		err = dec.UnmarshalText(enc)
		require.NoError(t, err)

		require.Equal(t, MAV_MANUAL_INPUT_SOURCE_NONE, dec)
	})
}
