//autogenerated:yes
//nolint:revive,govet,errcheck
package development

import (
	"testing"

	"github.com/stretchr/testify/require"
)

func TestEnum_EFI_PERFORMANCE_STATUS_FLAGS(t *testing.T) {
	t.Run("zero", func(t *testing.T) {
		var e EFI_PERFORMANCE_STATUS_FLAGS
		e.UnmarshalText([]byte{})
		e.MarshalText()
		e.String()
	})

	t.Run("first entry", func(t *testing.T) {
		enc, err := EFI_PERFORMANCE_STATUS_FLAGS_ENGINE_RUNNING.MarshalText()
		require.NoError(t, err)

		var dec EFI_PERFORMANCE_STATUS_FLAGS
		err = dec.UnmarshalText(enc)
		require.NoError(t, err)

		require.Equal(t, EFI_PERFORMANCE_STATUS_FLAGS_ENGINE_RUNNING, dec)
	})
}
