//autogenerated:yes
//nolint:revive,govet,errcheck
package common

import (
	"testing"

	"github.com/stretchr/testify/require"
)

func TestEnum_FOLLOW_TARGET_CAP_FLAGS(t *testing.T) {
	t.Run("zero", func(t *testing.T) {
		var e FOLLOW_TARGET_CAP_FLAGS
		e.UnmarshalText([]byte{})
		e.MarshalText()
		e.String()
	})

	t.Run("first entry", func(t *testing.T) {
		enc, err := FOLLOW_TARGET_CAP_FLAGS_POS.MarshalText()
		require.NoError(t, err)

		var dec FOLLOW_TARGET_CAP_FLAGS
		err = dec.UnmarshalText(enc)
		require.NoError(t, err)

		require.Equal(t, FOLLOW_TARGET_CAP_FLAGS_POS, dec)
	})
}
